Linux 2.2.8
Most of 2.2.8 by far is just architecture updates: arm, ppc and m68k stand
out as having been pretty much synchronized to their respective devel
trees, but there are some fixes to alpha and x86 too.

The one major fix in 2.2.8 is the SMP fix for disable_irq(), courtesy of
Andrea Arcangeli (I disagreed in details and did it differently in the
end, but all the heavy lifting was done by Andrea). This is the thing that
caused silenth deaths for some people with certain network adapters (3c509
and 8390-based cards in particular: the latter covers ne2000 clones which
are fairly common).

There are lots of smaller things (driver updates, filesystem cleanups and
some networking fixes), but the SMP irq thing is the one to kill for if
you happened to have any of the affected cards.

diff --git a/drivers/usb/restart b/drivers/usb/restart
--- a/drivers/usb/restart
+++ b/drivers/usb/restart
@@ -11,25 +11,28 @@ ME=`basename $0`
 #  fi
 #fi
 
-UPID=`ps aux | grep uhci-control | grep -v grep | awk '{print $2}'`
+UPID=`ps aux | grep ohci-control | grep -v grep | awk '{print $2}'`
 if test "$UPID"; then
   echo "$ME: killing $UPID"
   kill $UPID
 fi
 
-UMOD=`lsmod | grep '^usb-uhci' | grep -v grep`
+UMOD=`lsmod | grep '^usb-ohci' | grep -v grep`
 if test "$UMOD"; then
-  echo "$ME: removing usb-uhci.o"
+  echo "$ME: removing usb-ohci.o"
   sleep 1
-  if ! rmmod usb-uhci; then
-    echo "$ME: cannot remove usb-uhci.o"
+  if ! rmmod usb-ohci; then
+    echo "$ME: cannot remove usb-ohci.o"
     exit 1
   fi
 fi
 
 dmesg -c > /dev/null
 
-echo "$ME: starting usb-uhci.o"
-insmod -m usb-uhci.o > usb-uhci.map
-#echo "$ME: starting bp-mouse.o"
-#insmod -m bp-mouse.o > bp-mouse.map
+echo "$ME: starting usb-ohci.o"
+insmod -m usb-ohci.o > usb-ohci.map
+
+sleep 1
+UPID=`ps aux | grep ohci-control | grep -v grep | awk '{print $2}'`
+if test "$UPID"; then echo "$ME: ohci-control is pid $UPID" ; fi
+
